language: ruby
rvm:
  - 2.4.4
deploy:
  provider: heroku
  api_key:
    - secure: Diu5R7hBIcIywYONKcrVIEP8C7cH5Cl+QIGouz4j6IyCOO24X7uyhEnRBKF8bheYmXhxmc0FizDeWfyHR1IGrjsw5ZGowWaYokVpAuZTOw8ji+3fEK+qKGDjxJAv+jvDX1PbjXdkMNZv16v1CRlFjnOfJvMAeFiViHXxfKAo5YWcIQH1rprCKc8oeTXkb5ORkeduyHBROWHCuPBg2zAawax8/HxBxzfIvUGqGJsFhmr+rUMrFEXwhj98ArurOPP3AyaSdUEelh2UGOJ9FNQbSyyT8uksuTOJ/0AsEfRW4a6wTi+Qtl0O85LDO53+EhLDpJZVwu4/RbkmjuGmQoeAKS7Hrvb43oRuo3vyDgDzW1rnK1x/IvDB4Pk7WXUJl7CXrGbmzfRNfCaWFEgluWyYkxxmcU01p0z2P2jSFZhjw54+BgyiNaE4KAgXvBnNEvHqRd+YICA0pQZwnehNyTmnMxO4oXPHjxF+rvjfwjS5K7btbwqbWUCtTQUSJeGxLvizmhBP+mjbFiGfF4z18odLVejS11spqaVhsUE2tWNxH8W48VFMetVJt/NnDcF7EY0fAyXXFJEgufeqzah785rDGqQSoADbP/tY51rhDd5SNn4IYEy+r4UKFeaGYQIuHwEZufnGeowiuBuzfPKwizfJTBjI5Bk2egsHBDLDbCnPp+A=
  app: app-pizzza-db
  on:
    repo: ElomKossi/app-pizzza
