language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: TbmUzO6hYuJHcxKlHKIDCgajqBBzecsTMA9UDkffF3c+x0sJPh8bH/GCDgaQ+R3GQexef6+4hSPMw/yMAOOwSK8optZHAUGy+nGsAewcnEutDfYP2eP/CLpSdSvEydOyizcOPfhWfbeQ3QeGIBWO6jHTZwzfo1GVMo4l9C6RsfIk7gKlvken1P4HWda1DD/e0tJrHBafwPHJsQnvej/LIqfl5eiS2XmidfeTLG1VjiibOHAUWQOeQcirFzsvp7j+S98/sbgnngDGLfjs7/BvnkbMJ1otjkxH94Oi4pexIapgXDs3wULLofzexxuCW4MemVluaHBSK1/0GD4Zb8RCFex3UawCBI6eQlA5SSEzwy1w3HHTWF8KfOUiLb7tYm+ag4wdvuyIXlJaF9IuXuuBKX56DT1oevyiCZLJ7/fliB8/SS7mciu//4KJwG5B0+3nVVvxlMM6X8BiZA9dWqp6Q8Fdx2oxFKi+/PnCg/Z0DFVFFqv7PXO6rs+MwjMnf2HANT8kfU9R77wteHr+wZOetQFHwUFRgQW10wmHefHv0/BHPV8zwYm2nWRMdUPBO32MZgvDTR4fm8SewdSWE+mEWSigXUu6+tnl9PlNyeAYmElIZuzm+kMnT2VP50hTI3nv/an5YKc39+ZWK95NmW/JwW7jDS3FpSHIoCJJPwP9vag=
  app: app-pizzza
  on:
    repo: ElomKossi/app-pizzza
