language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: lDWMx0NkQwSufDRQxPVtCrck4SF2WnIeQELO/8NAt55ziR3NuS9G51E7/ZBM7vvvOWcWcMR1dxRCAZ7tUkcNGHz3eDhRW5pV7pp3eW2nXboJ9E+DknL1+j2MC+9pDOfZuxz59mBCAlhSO43rdWDmeFqi6oZ+bJLeAXfYlf6mCrI3bbvSxxf+zqosYr/16ZZ9+7QlQVQxzj+yTYCb0NnF8smlfbunCx4wrGeZDFzFPmN7Fqz6dPSqsmzRgH/lkSNV61IXBnhKQU7tzNC7UreYVQeVWNzalJzEeCKJ4s33YM1ZkununNVOXUqnmXqNyXVfoVzK1bNFl+5c3fd3Gey3QsRhvwj0GkIg7ldY71jNf5yE0xs/gmiPKqmNVbzY/eimBxcJPl7Xn8Ihly+YgjbLajKpVYz+yn+uuCPZ6B//Rw8iw+eUTukeAgH0dZaO5LUJ4RuyZlUaExfBm0bANxfb3XgZY/rhHfipwHbbSbnrxyS0EsFeaJ4WdK/OzaObsbHmJUiKPixzEqyHSYMxYSdU3NF3ePHA5BBsAFrfq+PvJYegaVMrd935r/kLdUZnEr87NqwO3wJn/FB2awrgugyeAlz9yNv05fmrloSj7vWNY7I9CYh/04PdnhIgyu786SDcyM2meJiFSVhshq2UZ82ibqAdOk9sBAif67/0gxT6NZI=
  app: app-pizzza
  on:
    repo: ElomKossi/app-pizzza
