language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: Yr9FBKRFrFS+Y4FurtQm3QnjILJCWD76R5lJ0Kcp+oQbnqIImCm7BuARr8Of4kWQhh/JjE07zCLrKVFDzJ8ZZDmiDk3sW+MNGd3RvkOBXyT/OBnce7p58fnZdZBM/GBB7lZcH+fzfMh5MnJwtldCf7MjLlu6Kvjm4kmOXgjIPBVPIjquMbQgWYVgyQTlqsY86J4RiRgkqlizwK2AgUEOXv2ps+QHAxYJHSi5GeaiOmU1UsGioWw9pJLTbsHUFMBV1YiwFScs7MN2UQseBWP7L1LMlAA/0ibBVSWPQNVRgymRJKss/gCl2QP5dp4l/NcCSxXbKT1GTQxOJIvt12SGD8GYHSoH/nT/4AVxb4yPXwX9R1SD9EpdKlon/qTyhABggMyS9PEvdZ+8W/cnpSr05vLDcvmAwIAM+ohY7JAHjvSzXnMX4NSCAdbXpeQTmUMLf5JWDgC7u8O0zUnhK4ejlLFPVMnIUu3iLaH5/Fq+ChK8zgolt9nc2WioUsPK40ENZvrtX4NGqIyfmEPqOeqYo0ceZclfdWkY24xIzqxnvoO4/ql6bCyukx4E98tjdiT14yqc2wi4qMeNd3aZXDgyL+aFlBMz3Livt/tnLPrDmBEPUJuYawxbPzuXcaX0M6ykSImQhogsSjrunJCH9x5qqTH7nHEDzVegaLJeRVJymHg=
  app: app-pizzza
  on:
    repo: ElomKossi/app-pizzza
